
language: node_js
node_js: [node]

before_install:
  # Export the C++11 compiler.
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
  # HACK: Right now `upath` is broken to not work in latest node, so we need
  # to ignore the engines field here.
  - yarn config set ignore-engines --global

cache:
  # Cache yarn packages.
  yarn: true

env:
  # Do two runs, one for testing and one for linting.
  matrix:
    - TEST_TYPE=test
    - TEST_TYPE=lint

script:
  # Build all of the packages so they are resolvable by each other.
  - yarn build
  # Run testing or linting depending on the environment.
  - yarn $TEST_TYPE
