name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: |
        yarn install
        yarn build
        yarn lint
        yarn test
      env:
        CI: true
